[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
    "hardhat/=node_modules/hardhat/",
    "xdeployer/=node_modules/xdeployer/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@ensdomains/=node_modules/@ensdomains/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat-deploy/=node_modules/hardhat-deploy/",
    "@uniswap/=contracts/uniswap"
]
auto-detect-solc=true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
